port: '/dev/ttyACM0'
baudrate: 921600
timeout: 3000
mode: 'absolute'  # should be 'relative' or 'absolute'
frame: 'imu_link'
frequency: 300
debug: false
magnetometer_enabled: true
timestamp_offset: 0.1
