y3space_imu:
  ros__parameters:
    debug: false
    magnetometer_enabled: false
    timestamp_offset: 0.012
    port: '/dev/ttyACM0'
    mode: 'relative'
    frame: 'imu_link'
    imu_topic: '/y3space/imu'
    baudrate: 115200
    timeout: 60000
    frequency: 400
