y3space_imu:
  ros__parameters:
    debug: false
    magnetometer_enabled: true
    tare: false
    timestamp_offset: 0.012
    port: '/dev/ttyYOST0'
    mode: 'relative'
    mi_mode: true
    frame: 'yost_imu'
    imu_topic: '/mavros/imu/data'
    baudrate: 115200
    timeout: 500
    frequency: 400
